### ISSUE TITLE
url too long error

### ISSUE THREAD

**Issue by jamesdixon** [SebastianOsuna/node-mapbox-static-paths#2]
Hi. Is there a way to get around this? I have an app that tracks walks and in some cases this error shows up.

**Comment by jamesdixon** [comment]
As a follow up, I had URL that was clocking in around 4300 characters. I decided to remove the url limit you imposed and everything seems to work as expected. That said, was there a specific reason for doing this other than some servers/browsers may balk at the length?

Thanks!

**Comment by SebastianOsuna** [comment]
According to the (now old) docs, the max url length is 4096 
https://www.mapbox.com/api-documentation/pages/static_classic.html

You can re-set the `MAX_PATH_POINTS` to try to drop some points in the middle.  
We could also move the `4096` to a property so it can be changed, if that'd work for you, let me know.

**Comment by jamesdixon** [comment]
@SebastianOsuna sorry for the delayed reply!

Yes, I think allowing these types of things to be configured would be great!

**Comment by jamesdixon** [comment]
@SebastianOsuna is there a way to configure this when instantiating the library?

**Comment by SebastianOsuna** [comment]
@jamesdixon See tag 1.1.4 ;)

**Comment by jamesdixon** [comment]
@SebastianOsuna awesome. thank you!
